server:
  port: 8080

spring:
  thymeleaf:
    cache: false
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 15MB
  mvc:
    favicon:
      enabled: false
